services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back_end_
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - network_om_pay
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: ${DB_HOST}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata_om_pay:/var/lib/postgresql/data
    networks:
      - network_om_pay

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - network_om_pay
    command: redis-server --appendonly yes

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/var/www 
    networks:
      - network_om_pay
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  pgdata_om_pay:
  jenkins_home:
  redis_data:

networks:
  network_om_pay:
